/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FmAppSetting: typeof import('./../ui/components/FmAppSetting/index.vue')['default']
    FmAuth: typeof import('./../ui/components/FmAuth/index.vue')['default']
    FmAvatar: typeof import('./../ui/components/FmAvatar/index.vue')['default']
    FmBadge: typeof import('./../ui/components/FmBadge/index.vue')['default']
    FmButton: typeof import('./../ui/components/FmButton/index.vue')['default']
    FmCard: typeof import('./../ui/components/FmCard/index.vue')['default']
    FmCheckbox: typeof import('./../ui/components/FmCheckbox/index.vue')['default']
    FmDivider: typeof import('./../ui/components/FmDivider/index.vue')['default']
    FmDrawer: typeof import('./../ui/components/FmDrawer/index.vue')['default']
    FmIcon: typeof import('./../ui/components/FmIcon/index.vue')['default']
    FmInput: typeof import('./../ui/components/FmInput/index.vue')['default']
    FmLoading: typeof import('./../ui/components/FmLoading/index.vue')['default']
    FmModal: typeof import('./../ui/components/FmModal/index.vue')['default']
    FmNotAllowed: typeof import('./../ui/components/FmNotAllowed/index.vue')['default']
    FmPageLayout: typeof import('./../ui/components/FmPageLayout/index.vue')['default']
    FmPageMain: typeof import('./../ui/components/FmPageMain/index.vue')['default']
    FmScrollArea: typeof import('./../ui/components/FmScrollArea/index.vue')['default']
    FmSelect: typeof import('./../ui/components/FmSelect/index.vue')['default']
    FmSlider: typeof import('./../ui/components/FmSlider/index.vue')['default']
    FmSwitch: typeof import('./../ui/components/FmSwitch/index.vue')['default']
    FmTabs: typeof import('./../ui/components/FmTabs/index.vue')['default']
    FmToast: typeof import('./../ui/components/FmToast/index.vue')['default']
    FmTrend: typeof import('./../ui/components/FmTrend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanFieldCalendar: typeof import('./../components/VanFieldCalendar/index.vue')['default']
    VanFieldDatePicker: typeof import('./../components/VanFieldDatePicker/index.vue')['default']
    VanFieldPicker: typeof import('./../components/VanFieldPicker/index.vue')['default']
  }
}
