/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/feature/': RouteRecordInfo<'/feature/', '/feature', Record<never, never>, Record<never, never>>,
    '/feature/component/basic': RouteRecordInfo<'/feature/component/basic', '/feature/component/basic', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/avatar/': RouteRecordInfo<'/feature/component/built_in/avatar/', '/feature/component/built_in/avatar', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/badge/': RouteRecordInfo<'/feature/component/built_in/badge/', '/feature/component/built_in/badge', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/button/': RouteRecordInfo<'/feature/component/built_in/button/', '/feature/component/built_in/button', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/card/': RouteRecordInfo<'/feature/component/built_in/card/', '/feature/component/built_in/card', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/checkbox/': RouteRecordInfo<'/feature/component/built_in/checkbox/', '/feature/component/built_in/checkbox', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/divider/': RouteRecordInfo<'/feature/component/built_in/divider/', '/feature/component/built_in/divider', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/drawer/': RouteRecordInfo<'/feature/component/built_in/drawer/', '/feature/component/built_in/drawer', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/input/': RouteRecordInfo<'/feature/component/built_in/input/', '/feature/component/built_in/input', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/loading/': RouteRecordInfo<'/feature/component/built_in/loading/', '/feature/component/built_in/loading', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/modal/': RouteRecordInfo<'/feature/component/built_in/modal/', '/feature/component/built_in/modal', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/page_main/': RouteRecordInfo<'/feature/component/built_in/page_main/', '/feature/component/built_in/page_main', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/scroll_area/': RouteRecordInfo<'/feature/component/built_in/scroll_area/', '/feature/component/built_in/scroll_area', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/select/': RouteRecordInfo<'/feature/component/built_in/select/', '/feature/component/built_in/select', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/slider/': RouteRecordInfo<'/feature/component/built_in/slider/', '/feature/component/built_in/slider', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/switch/': RouteRecordInfo<'/feature/component/built_in/switch/', '/feature/component/built_in/switch', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/tabs/': RouteRecordInfo<'/feature/component/built_in/tabs/', '/feature/component/built_in/tabs', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/toast/': RouteRecordInfo<'/feature/component/built_in/toast/', '/feature/component/built_in/toast', Record<never, never>, Record<never, never>>,
    '/feature/component/built_in/trend/': RouteRecordInfo<'/feature/component/built_in/trend/', '/feature/component/built_in/trend', Record<never, never>, Record<never, never>>,
    '/feature/component/composite': RouteRecordInfo<'/feature/component/composite', '/feature/component/composite', Record<never, never>, Record<never, never>>,
    '/feature/function/icon': RouteRecordInfo<'/feature/function/icon', '/feature/function/icon', Record<never, never>, Record<never, never>>,
    '/feature/function/keepAlive': RouteRecordInfo<'/feature/function/keepAlive', '/feature/function/keepAlive', Record<never, never>, Record<never, never>>,
    '/feature/function/unocss': RouteRecordInfo<'/feature/function/unocss', '/feature/function/unocss', Record<never, never>, Record<never, never>>,
    '/feature/navbar/custom-area': RouteRecordInfo<'/feature/navbar/custom-area', '/feature/navbar/custom-area', Record<never, never>, Record<never, never>>,
    '/feature/navbar/custom-navbar': RouteRecordInfo<'/feature/navbar/custom-navbar', '/feature/navbar/custom-navbar', Record<never, never>, Record<never, never>>,
    '/feature/navbar/default': RouteRecordInfo<'/feature/navbar/default', '/feature/navbar/default', Record<never, never>, Record<never, never>>,
    '/feature/navbar/none': RouteRecordInfo<'/feature/navbar/none', '/feature/navbar/none', Record<never, never>, Record<never, never>>,
    '/feature/page/loadmore': RouteRecordInfo<'/feature/page/loadmore', '/feature/page/loadmore', Record<never, never>, Record<never, never>>,
    '/feature/permission/': RouteRecordInfo<'/feature/permission/', '/feature/permission', Record<never, never>, Record<never, never>>,
    '/feature/permission/test': RouteRecordInfo<'/feature/permission/test', '/feature/permission/test', Record<never, never>, Record<never, never>>,
    '/feature/plugin/animation': RouteRecordInfo<'/feature/plugin/animation', '/feature/plugin/animation', Record<never, never>, Record<never, never>>,
    '/feature/plugin/echarts': RouteRecordInfo<'/feature/plugin/echarts', '/feature/plugin/echarts', Record<never, never>, Record<never, never>>,
    '/feature/plugin/esign': RouteRecordInfo<'/feature/plugin/esign', '/feature/plugin/esign', Record<never, never>, Record<never, never>>,
    '/feature/plugin/qrcode': RouteRecordInfo<'/feature/plugin/qrcode', '/feature/plugin/qrcode', Record<never, never>, Record<never, never>>,
    '/feature/plugin/swiper': RouteRecordInfo<'/feature/plugin/swiper', '/feature/plugin/swiper', Record<never, never>, Record<never, never>>,
    '/feature/plugin/vchart': RouteRecordInfo<'/feature/plugin/vchart', '/feature/plugin/vchart', Record<never, never>, Record<never, never>>,
    '/feature/tabbar/custom-area': RouteRecordInfo<'/feature/tabbar/custom-area', '/feature/tabbar/custom-area', Record<never, never>, Record<never, never>>,
    '/feature/tabbar/default': RouteRecordInfo<'/feature/tabbar/default', '/feature/tabbar/default', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'reload': RouteRecordInfo<'reload', '/reload', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
  }
}
