/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/feature/': RouteRecordInfo<'/feature/', '/feature', Record<never, never>, Record<never, never>>,
    '/feature/component/basic': RouteRecordInfo<'/feature/component/basic', '/feature/component/basic', Record<never, never>, Record<never, never>>,
    '/feature/component/built-in': RouteRecordInfo<'/feature/component/built-in', '/feature/component/built-in', Record<never, never>, Record<never, never>>,
    '/feature/component/pagemain-demo': RouteRecordInfo<'/feature/component/pagemain-demo', '/feature/component/pagemain-demo', Record<never, never>, Record<never, never>>,
    '/feature/component/trend-demo': RouteRecordInfo<'/feature/component/trend-demo', '/feature/component/trend-demo', Record<never, never>, Record<never, never>>,
    '/feature/function/icon': RouteRecordInfo<'/feature/function/icon', '/feature/function/icon', Record<never, never>, Record<never, never>>,
    '/feature/function/keepAlive': RouteRecordInfo<'/feature/function/keepAlive', '/feature/function/keepAlive', Record<never, never>, Record<never, never>>,
    '/feature/function/unocss': RouteRecordInfo<'/feature/function/unocss', '/feature/function/unocss', Record<never, never>, Record<never, never>>,
    '/feature/navbar/custom-area': RouteRecordInfo<'/feature/navbar/custom-area', '/feature/navbar/custom-area', Record<never, never>, Record<never, never>>,
    '/feature/navbar/custom-navbar': RouteRecordInfo<'/feature/navbar/custom-navbar', '/feature/navbar/custom-navbar', Record<never, never>, Record<never, never>>,
    '/feature/navbar/default': RouteRecordInfo<'/feature/navbar/default', '/feature/navbar/default', Record<never, never>, Record<never, never>>,
    '/feature/navbar/none': RouteRecordInfo<'/feature/navbar/none', '/feature/navbar/none', Record<never, never>, Record<never, never>>,
    '/feature/page/loadmore': RouteRecordInfo<'/feature/page/loadmore', '/feature/page/loadmore', Record<never, never>, Record<never, never>>,
    '/feature/permission/': RouteRecordInfo<'/feature/permission/', '/feature/permission', Record<never, never>, Record<never, never>>,
    '/feature/permission/test': RouteRecordInfo<'/feature/permission/test', '/feature/permission/test', Record<never, never>, Record<never, never>>,
    '/feature/plugin/animation': RouteRecordInfo<'/feature/plugin/animation', '/feature/plugin/animation', Record<never, never>, Record<never, never>>,
    '/feature/plugin/echarts': RouteRecordInfo<'/feature/plugin/echarts', '/feature/plugin/echarts', Record<never, never>, Record<never, never>>,
    '/feature/plugin/esign': RouteRecordInfo<'/feature/plugin/esign', '/feature/plugin/esign', Record<never, never>, Record<never, never>>,
    '/feature/plugin/qrcode': RouteRecordInfo<'/feature/plugin/qrcode', '/feature/plugin/qrcode', Record<never, never>, Record<never, never>>,
    '/feature/plugin/swiper': RouteRecordInfo<'/feature/plugin/swiper', '/feature/plugin/swiper', Record<never, never>, Record<never, never>>,
    '/feature/plugin/vchart': RouteRecordInfo<'/feature/plugin/vchart', '/feature/plugin/vchart', Record<never, never>, Record<never, never>>,
    '/feature/tabbar/custom-area': RouteRecordInfo<'/feature/tabbar/custom-area', '/feature/tabbar/custom-area', Record<never, never>, Record<never, never>>,
    '/feature/tabbar/default': RouteRecordInfo<'/feature/tabbar/default', '/feature/tabbar/default', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'reload': RouteRecordInfo<'reload', '/reload', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
  }
}
