/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAuth: typeof import('./../components/AppAuth/index.vue')['default']
    AppNotAllowed: typeof import('./../components/AppNotAllowed/index.vue')['default']
    AppPageLayout: typeof import('./../components/AppPageLayout/index.vue')['default']
    AppSetting: typeof import('./../components/AppSetting/index.vue')['default']
    FmAvatar: typeof import('@fantastic-mobile/components')['FmAvatar']
    FmBadge: typeof import('@fantastic-mobile/components')['FmBadge']
    FmButton: typeof import('@fantastic-mobile/components')['FmButton']
    FmButtonGroup: typeof import('@fantastic-mobile/components')['FmButtonGroup']
    FmCard: typeof import('@fantastic-mobile/components')['FmCard']
    FmCheckbox: typeof import('@fantastic-mobile/components')['FmCheckbox']
    FmDivider: typeof import('@fantastic-mobile/components')['FmDivider']
    FmDrawer: typeof import('@fantastic-mobile/components')['FmDrawer']
    FmIcon: typeof import('@fantastic-mobile/components')['FmIcon']
    FmInput: typeof import('@fantastic-mobile/components')['FmInput']
    FmLoading: typeof import('@fantastic-mobile/components')['FmLoading']
    FmModal: typeof import('@fantastic-mobile/components')['FmModal']
    FmPageMain: typeof import('@fantastic-mobile/components')['FmPageMain']
    FmScrollArea: typeof import('@fantastic-mobile/components')['FmScrollArea']
    FmSelect: typeof import('@fantastic-mobile/components')['FmSelect']
    FmSlider: typeof import('@fantastic-mobile/components')['FmSlider']
    FmSwitch: typeof import('@fantastic-mobile/components')['FmSwitch']
    FmTabs: typeof import('@fantastic-mobile/components')['FmTabs']
    FmToast: typeof import('@fantastic-mobile/components')['FmToast']
    FmTrend: typeof import('@fantastic-mobile/components')['FmTrend']
    VanFieldCalendar: typeof import('./../components/VanFieldCalendar/index.vue')['default']
    VanFieldDatePicker: typeof import('./../components/VanFieldDatePicker/index.vue')['default']
    VanFieldPicker: typeof import('./../components/VanFieldPicker/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AppAuth: typeof import('./../components/AppAuth/index.vue')['default']
  const AppNotAllowed: typeof import('./../components/AppNotAllowed/index.vue')['default']
  const AppPageLayout: typeof import('./../components/AppPageLayout/index.vue')['default']
  const AppSetting: typeof import('./../components/AppSetting/index.vue')['default']
  const FmAvatar: typeof import('@fantastic-mobile/components')['FmAvatar']
  const FmBadge: typeof import('@fantastic-mobile/components')['FmBadge']
  const FmButton: typeof import('@fantastic-mobile/components')['FmButton']
  const FmButtonGroup: typeof import('@fantastic-mobile/components')['FmButtonGroup']
  const FmCard: typeof import('@fantastic-mobile/components')['FmCard']
  const FmCheckbox: typeof import('@fantastic-mobile/components')['FmCheckbox']
  const FmDivider: typeof import('@fantastic-mobile/components')['FmDivider']
  const FmDrawer: typeof import('@fantastic-mobile/components')['FmDrawer']
  const FmIcon: typeof import('@fantastic-mobile/components')['FmIcon']
  const FmInput: typeof import('@fantastic-mobile/components')['FmInput']
  const FmLoading: typeof import('@fantastic-mobile/components')['FmLoading']
  const FmModal: typeof import('@fantastic-mobile/components')['FmModal']
  const FmPageMain: typeof import('@fantastic-mobile/components')['FmPageMain']
  const FmScrollArea: typeof import('@fantastic-mobile/components')['FmScrollArea']
  const FmSelect: typeof import('@fantastic-mobile/components')['FmSelect']
  const FmSlider: typeof import('@fantastic-mobile/components')['FmSlider']
  const FmSwitch: typeof import('@fantastic-mobile/components')['FmSwitch']
  const FmTabs: typeof import('@fantastic-mobile/components')['FmTabs']
  const FmToast: typeof import('@fantastic-mobile/components')['FmToast']
  const FmTrend: typeof import('@fantastic-mobile/components')['FmTrend']
  const VanFieldCalendar: typeof import('./../components/VanFieldCalendar/index.vue')['default']
  const VanFieldDatePicker: typeof import('./../components/VanFieldDatePicker/index.vue')['default']
  const VanFieldPicker: typeof import('./../components/VanFieldPicker/index.vue')['default']
}